permalink: /:year/:month/:day/:title
paginate: 10
markdown: kramdown
highlighter: true

kramdown:
  input: GFM

author: 
  name: 李树杰 
  email: lishujie911@gmail.com
  link: http://lihuaib.org

# avatar头像及Favicon
avatar: https://raw.githubusercontent.com/lihuaib/lihuaib.github.com/master/assets/img/avatar.jpg

title: lihuaib的博客 
locals:
  tags: 标签页
  about: 关于我
  archive: 归档 
active: 技术技巧
subscribe_rss: /pages/atom.xml

# disqus 设置
disqus:
  shortname: lihuaib
